### ISSUE TITLE
How can I create my own add-on?

### ISSUE THREAD

**Issue by Darker** [Snowl/LoLEnhancementSuite#46]
Hello,
LES is really great! I also like the structure a lot. But the source-code of the mods looks like some low-level bytecode and is not easy to understand.

Could you post some tips how did you get to make this? I'd sure appreciate it!

**Comment by Snowl** [comment]
Hey Darker

The bytecode is decoded Actionscript. You can use JPEXS free decompiler to decompile the .dat files manually and then edit through there, which allows editing in both byte-code and actionscript.

Thanks,
Snowl

**Comment by Darker** [comment]
Which dat files do you mean? I now actually just need to decompile the launcher to find out how why it keeps deleting my profile settings (including item sets). And I have no idea how to do it :(

**Comment by fish220** [comment]
Darker the people of Rimworld need your map editor again. We need you to update the editor for the forums again.

**Comment by Snowl** [comment]
They are located at League of Legends\RADS\projects\lol_air_client\releases\x\deploy\lib and League of Legends\RADS\projects\lol_air_client\releases\x\deploy\mod
