### ISSUE TITLE
2 of Antropod's mods not working

### ISSUE THREAD

**Issue by ablast6** [Snowl/LoLEnhancementSuite#49]
Join multiples Queues and Select Random skin are both greyed out and unable to be selected. This is especially annoying as this is the only way to get a Select Random skins mod. This is on Windows 8.1.

![lol es error](https://cloud.githubusercontent.com/assets/12902909/8172555/79a52c4c-1387-11e5-8f1e-271206024e94.png)

**Comment by Snowl** [comment]
Yes, they don't work so they have been greyed out
