### ISSUE TITLE
Skinny Bots not working

### ISSUE THREAD

**Issue by ZhunCn** [snowl/LoLEnhancementSuite#51]
I have the Skinny Bots mod patched, but it doesn't show the second tab for skins in custom games at all. Looks like the normal select screen before hand with only champions and difficulty tabs.
![skinny bots](https://cloud.githubusercontent.com/assets/15008619/10329134/797aed16-6c82-11e5-84cb-b32f6803c89e.png)

**Comment by snowl** [comment]
You need to re-patch each time there is a new patch. Try re-installing LoLEnhancementSuite and it should be working again.
