### ISSUE TITLE
Skinny Bots not working on 5.23 Update

### ISSUE THREAD

**Issue by Kingdemonic666** [snowl/LoLEnhancementSuite#56]
it bugs when adding a bot, leaving blank spaces and freezing on that screen when it changes (like shop, champ selection, etc) tried lastest version and the past ones...
![lolclient 2015-11-26 13-13-53-82](https://cloud.githubusercontent.com/assets/6070287/11426002/172da9ba-9440-11e5-9a2c-7db4840ec73e.png)
![lolclient 2015-11-26 13-13-56-73](https://cloud.githubusercontent.com/assets/6070287/11426003/17c081a4-9440-11e5-8151-64f28e22429b.png)

**Comment by snowl** [comment]
Will be fixed ASAP.

**Comment by snowl** [comment]
Fixed!
