### ISSUE TITLE
Issues with latest patch

### ISSUE THREAD

**Issue by snowl** [snowl/LoLEnhancementSuite#57]
Since LoLEnhancementSuite has moved to a different version detection schema (it retrieves versions it's compatible with from the internet), there is the possibility that it may have some compatibility issues that have turned up. I do my best to check for any issues but if any extra issues are created with the current League of Legends patch then please report them in this issue (instead of creating a new issue).

Current known issues with the latest League of Legends patch:
- Join Multiple Queues is currently broken and needs to be re-implemented for each patch. This modification has not been updated since 5.11

Thanks,
Snowl.

**Comment by frostycpu** [comment]
I'll eventually fix join multiple queues when I have the time. The current implementation is hard to work with, so it probably needs to be reworked.
