### ISSUE TITLE
How do i patch it my self without LES?

### ISSUE THREAD

**Issue by chienhao10** [snowl/LoLEnhancementSuite#59]
hi i just want to use fake status, can i just down the mod and replace in some file in league of legends?
i don't want to use LES since i only use 1 mod, i can just easily copy and paste and make back ups

**Comment by secretdataz** [comment]
No, you have to decompile some of the AIR client and edit its code. LES does that for you. Otherwise, you have to do it manually.

**Comment by chienhao10** [comment]
thx, i am trying to decompile some of the AIR client and edit its code. i wanted to see how to do it manually. is there a list of files that i have to edit for fake status and other mods?

**Comment by frostycpu** [comment]
You can select which mods you want to patch. If you don't want certain features just uncheck them and they won't be patched into your client.
