### ISSUE TITLE
Post 6.5 patch.

### ISSUE THREAD

**Issue by P4IN** [snowl/LoLEnhancementSuite#64]
Hey Snowl,

Thank you for the great job your putting in LES. It helps a lot.
Anyway, after patch 6.5, installing LES (I only tick the appear offline addon) makes the LoL client chat disappears completely,which includes summoner name, friend list and most importantly the chat function.
Can you solve this issue please?

Thanks again.

**Comment by Applejuicyz** [comment]
I just want to say that I'm experiencing the same problem. These 8 days have made me realize how much I use LESS on a daily basis and I just wanted to say thanks for the amazing work, Snowl.

**Comment by xPaultje** [comment]
Jo Guys,

i've tweaked the mod.json file abit from appearoffline and now i got it to work, the only thing that doesnt work is the option to show your offline friends. So you can click the appear offline button, but there is no way to see all your offline friends tho.


how to do it,
go to your LeagueEnhancementSuite6b folder, click mods, appearOffline, mod.json

and replace the text with this:
**{
	"Name": "Appear Offline",
	"Description": "Adds an option to appear offline in the chat options. You appear invisible to everyone, but all chat functions still remain.",
	"Author": "Snowl",
	"Library": "AbcSharp",
	"DisabledByDefault": false,
	"Patches":
	[
		{
			"Swf": "mod/ser/mod_ser.dat",
			"Class": "com.riotgames.platform.gameclient.module.services.lcds:ChatServiceImpl",
			"Action": "replace_trait",
			"Code": "patch1.asasm"
		},
		{
			"Swf": "mod/cht/mod_cht.dat",
			"Class": "com.riotgames.pvpnet.docked.chat.view.buddypanel:FriendsListOptionsPanel",
			"Action": "replace_trait",
			"Code": "patch2.asasm"
		},
		{
			"Swf": "mod/cht/mod_cht.dat",
			"Class": "com.riotgames.pvpnet.docked.chat.view.buddypanel:FriendsListOptionsPanel",
			"Action": "replace_trait",
			"Code": "patch11.asasm"
		}
	]
}**


then save.
After that run the program and patch, hf guys!

**Comment by P4IN** [comment]
It actually works!  You are a life saver! Thanks man.

**Comment by P4IN** [comment]
@xPaultje Hmmm, I just realized that the appear offline option does not work even tho it's enabled, as my friend just messaged me while it was enabled. We need help from the devs themselves. @snowl @frostycpu

**Comment by Applejuicyz** [comment]
That's odd, for me it worked! I do have to un-check and check the offline option every time I log in though, but my friends can't see me.
Thanks, Paultje!

**Comment by P4IN** [comment]
@Applejuicyz can you please attach your mod,json file? Thank you.

**Comment by P4IN** [comment]
@Applejuicyz can you attach your mod.json file please? Thank you.

**Comment by Applejuicyz** [comment]
@P4IN It's the exact same as Paultje posted - I just un-check the offline option and then check it again to appear offline. Have you tried this?

**Comment by P4IN** [comment]
Yeah, i did. But i don't know why it didn't work. If you could attach your file i would be grateful.

**Comment by P4IN** [comment]
Just drag it here.

**Comment by xPaultje** [comment]
Hello,

i just checked on 2 Pc's toggling the option appear offline on and off and it works.

i cant drag the file here, gives an error even when i compress it to .zip. 
just use my guide, copy, paste and then save.

it also worked for me right from when i login, i dont even need to tick it off/on/off or on/off to make it work.

idk how your friend could see you were online, or maybe he was on the riot friend mobile app? maybe those can see you, can't check that right now.

**Comment by P4IN** [comment]
You might be right. It could be actually related to the Riot mobile app. I'm still not sure tho.

**Comment by frostycpu** [comment]
Hey guys, semester just started for me so I'm a little bit short on time, but I might look into it in a few days (if @snowl isn't faster).

**Comment by P4IN** [comment]
We totally understand. Thank you for your time. @frostycpu

**Comment by frostycpu** [comment]
Should be fixed with 9230298e7a92897f7b15b68668c74b42dfe644fa.

**Comment by snowl** [comment]
Updated the hosted file.
