### ISSUE TITLE
Appear Offline Bug

### ISSUE THREAD

**Issue by xPaultje** [snowl/LoLEnhancementSuite#66]
Hello,

it seems like the appear offline option is bugged or something,
people can still see me when and send messages to me.
even if i untick/tick appear offline button again it stays bugged.

people also can't invite me, they get a message about how i dont meet the requirements to join or something.

Don't know how to fix this myself.

**Comment by P4IN** [comment]
I am still having this problem too even after the last fix :/ The apear offline option is still bugged. @frostycpu @snowl

**Comment by d3xMachina** [comment]
I'm so sad this tool is not updated as often as before, specialy for appearoffline and skinnybots :(

**Comment by d3xMachina** [comment]
I'm so sad this tool is not updated as often as before, specialy for appearoffline and skinnybots :(

**Comment by frostycpu** [comment]
Yea, y u no update @snowl ლ(ಠ益ಠლ).

But on a serious note, I'm pretty busy with university and so is snowl I guess .

I noticed that something is wrong with appearOffline, but I didn't find out what's causing it so if you have any additional information post it here.

**Comment by Lainerd** [comment]
I think it has something to do with the new clubs.
